import {
  Client,
  Events,
  GatewayIntentBits,
  MessageType,
  Partials,
  type Message,
} from "discord.js";

import { env, requireEnv } from "../config/env.js";
import { logger } from "../lib/logger.js";
import {
  DiscordAssistantBinding,
  type DiscordAssistantBindingDocument,
} from "../models/DiscordAssistantBinding.js";
import {
  askOpenClawAssistant,
  downloadRuntimeGeneratedFile,
  type RuntimeGeneratedFile,
} from "../openclaw/client.js";
import {
  buildReferenceId,
  categorizeError,
  friendlyRuntimeErrorMessage,
} from "../openclaw/errors.js";
import {
  launchDiscordLongOperationJob,
  resumeStaleAssistantJobs,
} from "./longJobLauncher.js";
import { detectLongRunningOperation } from "./longOps.js";
import {
  detectProtectedFileRequest,
  guardOutboundFileBytes,
  guardOutboundText,
  SECRET_REFUSAL_MESSAGE,
} from "../security/secretGuard.js";

import {
  attachmentRejectionMessage,
  MAX_ATTACHMENTS,
  normalizeDiscordAttachments,
  skippedAttachmentsNote,
  type RawDiscordAttachment,
} from "./attachments.js";
import {
  extractSpreadsheetText,
  extractTextFile,
  isInlineTextAttachment,
  isSpreadsheetAttachment,
} from "./spreadsheets.js";
import {
  extractPresentationText,
  isPresentationAttachment,
} from "./presentations.js";

type MessageGatewayStatus = {
  enabled: boolean;
  connected: boolean;
};

export type LongOperationJobRequest = {
  opType: string;
  ask: Parameters<typeof askOpenClawAssistant>[0];
  messageId: string;
  conversationId: string;
  guildId: string;
  channelId: string;
  threadId?: string;
  ack: (content: string) => Promise<unknown>;
  notify: (content: string) => Promise<unknown>;
  sendFiles?: (caption: string, files: DiscordFilePayload[]) => Promise<unknown>;
  timeoutMs?: number;
  skipAck?: boolean;
  ackMode?: "immediate" | "delayed";
  ackDelayMs?: number;
  quiet?: boolean;
};

type MessageGatewayDeps = {
  findBinding: (input: {
    guildId: string;
    channelId: string;
  }) => Promise<DiscordAssistantBindingDocument | null>;
  askAssistant: typeof askOpenClawAssistant;
  logger: typeof logger;
  runLongOperationJob?: (request: LongOperationJobRequest) => Promise<unknown>;
  fetchRuntimeFile?: typeof downloadRuntimeGeneratedFile;
};

export const buildRuntimeFilePayloads = async (
  openclawUrl: string,
  files: RuntimeGeneratedFile[],
  fetchRuntimeFile: typeof downloadRuntimeGeneratedFile,
): Promise<{
  payloads: DiscordFilePayload[];
  failed: string[];
  blocked: string[];
}> => {
  const payloads: DiscordFilePayload[] = [];
  const failed: string[] = [];
  const blocked: string[] = [];

  for (const file of files.slice(0, 5)) {
    try {
      const bytes = await fetchRuntimeFile(openclawUrl, file.fileId);
      // Layer 2: scan generated bytes before upload.
      if (guardOutboundFileBytes(bytes, file.filename).action === "block") {
        blocked.push(file.filename);
        continue;
      }
      payloads.push({ attachment: bytes, name: file.filename });
    } catch {
      failed.push(file.filename);
    }
  }

  return { payloads, failed, blocked };
};

export type DiscordFilePayload = {
  attachment: Buffer;
  name: string;
};

type SendableDiscordChannel = {
  sendTyping: () => Promise<void>;
  send: (payload: {
    content: string;
    allowedMentions: { repliedUser: false };
    files?: DiscordFilePayload[];
  }) => Promise<unknown>;
  isThread?: () => boolean;
  parentId?: string | null;
  name?: string | null;
  parent?: { name?: string | null } | null;
};

const DISCORD_MESSAGE_LIMIT = 2000;
const DEFAULT_REPLY_CHUNK_LIMIT = 1900;
const PROCESSED_MESSAGE_TTL_MS = 5 * 60 * 1000;
const PROCESSED_MESSAGE_MAX_SIZE = 5000;
const TYPING_REFRESH_INTERVAL_MS = 8000;

export const buildDiscordConversationId = (input: {
  guildId: string;
  channelId: string;
  threadId?: string;
}) =>
  [
    "discord",
    input.guildId,
    input.channelId,
    ...(input.threadId ? [input.threadId] : []),
  ].join(":");

export const resolveDiscordMessageTarget = (message: {
  channelId: string;
  channel?: unknown;
}) => {
  const channel = (message.channel ?? {}) as SendableDiscordChannel;
  const isThread =
    typeof channel.isThread === "function" && Boolean(channel.isThread());

  if (isThread && channel.parentId) {
    return {
      bindingChannelId: channel.parentId,
      threadId: message.channelId,
      threadName: channel.name ?? undefined,
      channelName: channel.parent?.name ?? undefined,
    };
  }

  return {
    bindingChannelId: message.channelId,
    threadId: undefined,
    threadName: undefined,
    channelName: channel.name ?? undefined,
  };
};

const status: MessageGatewayStatus = {
  enabled: env.DISCORD_MESSAGE_GATEWAY_ENABLED === "true",
  connected: false,
};

let startedClient: Client | null = null;

export const getDiscordMessageGatewayStatus = () => ({ ...status });

export const createTtlMessageCache = (
  ttlMs = PROCESSED_MESSAGE_TTL_MS,
  maxSize = PROCESSED_MESSAGE_MAX_SIZE,
) => {
  const processed = new Map<string, number>();

  const prune = (now = Date.now()) => {
    for (const [messageId, expiresAt] of processed.entries()) {
      if (expiresAt <= now || processed.size > maxSize) {
        processed.delete(messageId);
      }
    }
  };

  return {
    has(messageId: string) {
      prune();
      return processed.has(messageId);
    },
    add(messageId: string) {
      prune();
      processed.set(messageId, Date.now() + ttlMs);
    },
    size() {
      prune();
      return processed.size;
    },
  };
};

export const createPerChannelQueue = () => {
  const queues = new Map<string, Promise<void>>();

  const enqueue = (key: string, task: () => Promise<void>) => {
    const previous = queues.get(key) ?? Promise.resolve();
    const next = previous
      .catch(() => {
        // Previous failures are already logged by the task.
      })
      .then(task)
      .finally(() => {
        if (queues.get(key) === next) {
          queues.delete(key);
        }
      });

    queues.set(key, next);
    return next;
  };

  return { enqueue };
};

export const splitDiscordMessage = (
  input: string,
  limit = DEFAULT_REPLY_CHUNK_LIMIT,
) => {
  const text = input.trim() || "The assistant returned an empty response.";

  if (limit <= 0 || limit > DISCORD_MESSAGE_LIMIT) {
    throw new Error("Invalid Discord message split limit");
  }

  const chunks: string[] = [];
  let current = "";

  for (const char of text) {
    if (current.length + char.length > limit) {
      chunks.push(current);
      current = "";
    }

    current += char;
  }

  if (current) {
    chunks.push(current);
  }

  return chunks;
};

const isSystemMessage = (message: Pick<Message, "system" | "type">) =>
  Boolean(message.system) || message.type !== MessageType.Default;

export const shouldIgnoreDiscordMessage = (
  message: Pick<
    Message,
    "guildId" | "channelId" | "content" | "webhookId" | "system" | "type"
  > & {
    id: string;
    author?: { bot?: boolean; id?: string };
    attachments?: { size?: number };
  },
  clientUserId?: string,
) => {
  if (!message.guildId || !message.channelId) {
    return true;
  }

  if (message.author?.bot || message.webhookId) {
    return true;
  }

  if (clientUserId && message.author?.id === clientUserId) {
    return true;
  }

  if (isSystemMessage(message as Pick<Message, "system" | "type">)) {
    return true;
  }

  if (!message.content.trim() && !(message.attachments?.size ?? 0)) {
    return true;
  }

  return false;
};

const getRawAttachments = (message: Message): RawDiscordAttachment[] =>
  message.attachments.map((attachment) => ({
    filename: attachment.name,
    contentType: attachment.contentType,
    size: attachment.size,
    url: attachment.url,
  }));


export const handleDiscordMessage = async (
  message: Message,
  deps: MessageGatewayDeps,
) => {
  const guildId = message.guildId;
  const channelId = message.channelId;

  if (!guildId || !channelId) {
    return;
  }

  const target = resolveDiscordMessageTarget(message);
  const binding = await deps.findBinding({
    guildId,
    channelId: target.bindingChannelId,
  });

  if (!binding) {
    return;
  }

  const channel = message.channel as Partial<SendableDiscordChannel>;

  if (
    typeof channel.sendTyping !== "function" ||
    typeof channel.send !== "function"
  ) {
    deps.logger.error("Discord message handling failed", {
      guildId,
      channelId,
      messageId: message.id,
      assistantId: binding.assistantId,
      error: "Discord channel is not sendable",
    });
    return;
  }

  const conversationId = buildDiscordConversationId({
    guildId,
    channelId: target.bindingChannelId,
    threadId: target.threadId,
  });

  const rawAttachments = getRawAttachments(message);
  // The model reads INLINE text reliably but treats file attachments
  // (input_file) inconsistently. So spreadsheets (converted xlsx->CSV) AND text
  // files (csv/txt/md/json/html/…) are inlined into the prompt; only PDFs and
  // images are passed through as real attachments.
  const inlineRaw = rawAttachments.filter(
    (a) =>
      isSpreadsheetAttachment(a.filename, a.contentType) ||
      isPresentationAttachment(a.filename, a.contentType) ||
      isInlineTextAttachment(a.filename, a.contentType),
  );
  const { supported: attachments, skipped } = normalizeDiscordAttachments(
    rawAttachments.filter(
      (a) =>
        !isSpreadsheetAttachment(a.filename, a.contentType) &&
        !isPresentationAttachment(a.filename, a.contentType) &&
        !isInlineTextAttachment(a.filename, a.contentType),
    ),
  );
  let question = message.content.trim();

  if (inlineRaw.length > 0) {
    const parts: string[] = [];
    for (const a of inlineRaw.slice(0, MAX_ATTACHMENTS)) {
      const text = isSpreadsheetAttachment(a.filename, a.contentType)
        ? await extractSpreadsheetText({
            filename: a.filename ?? "spreadsheet",
            url: a.url ?? "",
            contentType: a.contentType,
            size: Number(a.size) || 0,
          })
        : isPresentationAttachment(a.filename, a.contentType)
        ? await extractPresentationText({
            filename: a.filename ?? "presentation",
            url: a.url ?? "",
            contentType: a.contentType,
            size: Number(a.size) || 0,
          })
        : await extractTextFile({
            filename: a.filename ?? "file",
            url: a.url ?? "",
            size: Number(a.size) || 0,
          });
      if (text) parts.push(text);
    }
    const joined = parts.join("\n\n");
    if (joined) question = [question, joined].filter(Boolean).join("\n\n");
    deps.logger.info("Discord file attachments inlined", {
      guildId,
      assistantId: binding.assistantId,
      count: inlineRaw.length,
      chars: joined.length,
    });
  }

  // Layer 1: deny protected-file/config disclosure requests before OpenClaw.
  const inboundDetection = detectProtectedFileRequest(question);
  if (inboundDetection.blocked) {
    deps.logger.info("Discord protected-file request denied", {
      guildId,
      channelId,
      messageId: message.id,
      assistantId: binding.assistantId,
      category: inboundDetection.category,
    });
    await channel
      .send?.({
        content: SECRET_REFUSAL_MESSAGE,
        allowedMentions: { repliedUser: false },
      })
      .catch(() => undefined);
    return;
  }

  if (!question && attachments.length === 0) {
    if (skipped.length > 0) {
      await channel
        .send?.({
          content: attachmentRejectionMessage(skipped),
          allowedMentions: { repliedUser: false },
        })
        .catch(() => undefined);
    }
    return;
  }

  if (attachments.length > 0 || skipped.length > 0) {
    deps.logger.info("Discord attachments received", {
      guildId,
      channelId,
      messageId: message.id,
      assistantId: binding.assistantId,
      attachmentCount: attachments.length + skipped.length,
      supportedCount: attachments.length,
      skippedCount: skipped.length,
      contentTypes: attachments.map((item) => item.contentType),
      totalBytes: attachments.reduce((sum, item) => sum + item.size, 0),
    });
  }

  const askInput = {
    openclawUrl: binding.openclawUrl,
    tenantId: binding.tenantId,
    assistantId: binding.assistantId,
    runtimeKind: binding.runtimeKind || "openclaw",
    question,
    user: {
      id: message.author.id,
      username: message.author.username,
    },
    discord: {
      guildId,
      channelId: target.bindingChannelId,
      guildName: message.guild?.name ?? undefined,
      channelName: target.channelName,
      threadId: target.threadId,
      threadName: target.threadName,
      messageId: message.id,
      userId: message.author.id,
      username: message.author.username,
      authorDisplayName: message.member?.displayName ?? undefined,
      responseMode: binding.responseMode,
      conversationId,
      attachments,
    },
  };

  const skippedNote =
    skipped.length > 0 ? skippedAttachmentsNote(skipped) : null;

  const sendSkippedNote = async () => {
    if (skippedNote) {
      await channel
        .send?.({
          content: skippedNote,
          allowedMentions: { repliedUser: false },
        })
        .catch(() => undefined);
    }
  };

  const detectedOpType = detectLongRunningOperation(message.content);
  const hasFileAttachment = attachments.some((item) => item.kind === "file");
  const opType =
    detectedOpType ?? (hasFileAttachment ? "file-processing" : null);

  // Async-first: every Discord message runs through the runtime job path so
  // slow model answers cannot hit the sync request timeout. Long operations
  // keep their immediate "Started…" ack; normal chat acks only if the answer
  // is still pending after the configured delay.
  if (deps.runLongOperationJob) {
    const isLongOp = Boolean(opType);

    // For normal chat the first outbound message (delayed ack or the final
    // answer, whichever comes first) replies to the user's message; the rest
    // go to the channel/thread like the old sync path did.
    let firstOutbound = true;
    const replyOrSend = (content: string) => {
      if (firstOutbound) {
        firstOutbound = false;
        return message.reply({
          content,
          allowedMentions: { repliedUser: false },
        });
      }
      return channel.send!({
        content,
        allowedMentions: { repliedUser: false },
      });
    };

    let typingRefresh: ReturnType<typeof setInterval> | undefined;
    if (!isLongOp) {
      await Promise.resolve(channel.sendTyping?.()).catch(() => undefined);
      typingRefresh = setInterval(() => {
        void Promise.resolve(channel.sendTyping?.()).catch(() => undefined);
      }, TYPING_REFRESH_INTERVAL_MS);
    }

    void deps
      .runLongOperationJob({
        opType: opType ?? "chat",
        ask: askInput,
        messageId: message.id,
        conversationId,
        guildId,
        channelId: target.bindingChannelId,
        threadId: target.threadId,
        ack: isLongOp
          ? (content: string) =>
              message.reply({ content, allowedMentions: { repliedUser: false } })
          : replyOrSend,
        notify: isLongOp
          ? (content: string) =>
              channel.send!({ content, allowedMentions: { repliedUser: false } })
          : replyOrSend,
        sendFiles: (caption: string, files: DiscordFilePayload[]) =>
          channel.send!({
            content: caption,
            allowedMentions: { repliedUser: false },
            files,
          }),
        ackMode: isLongOp ? "immediate" : "delayed",
        quiet: !isLongOp,
      })
      .catch((error) => {
        deps.logger.error("Discord assistant job failed to start", {
          guildId,
          channelId,
          messageId: message.id,
          assistantId: binding.assistantId,
          error: error instanceof Error ? error.message : String(error),
        });
      })
      .finally(() => {
        if (typingRefresh) clearInterval(typingRefresh);
      });
    await sendSkippedNote();
    return;
  }

  let typingRefresh: ReturnType<typeof setInterval> | undefined;

  try {
    await channel.sendTyping();
    typingRefresh = setInterval(() => {
      void channel.sendTyping?.().catch(() => undefined);
    }, TYPING_REFRESH_INTERVAL_MS);

    // On the second retry (≥20s of waiting) tell the user we're on it — a
    // busy/restarting runtime otherwise looks like being ignored.
    let retryNoticeSent = false;
    const result = await deps.askAssistant(askInput, {
      onRetry: ({ attempt }) => {
        deps.logger.info("Discord ask retrying against runtime", {
          guildId,
          channelId,
          messageId: message.id,
          assistantId: binding.assistantId,
          attempt,
        });
        if (attempt === 2 && !retryNoticeSent) {
          retryNoticeSent = true;
          void channel
            .send?.({
              content:
                "The assistant is busy or restarting — retrying automatically, hang on.",
              allowedMentions: { repliedUser: false },
            })
            .catch(() => undefined);
        }
      },
    });
    const askResult =
      typeof result === "string"
        ? { answer: result, files: [], fileErrors: [] }
        : {
            answer: result.answer,
            files: result.files ?? [],
            fileErrors: result.fileErrors ?? [],
          };

    // Layer 3: scan/redact/block outbound text before sending to Discord.
    const textGuard = guardOutboundText(askResult.answer);
    if (textGuard.action !== "allow") {
      deps.logger.info("Discord outbound text guarded", {
        guildId,
        channelId,
        messageId: message.id,
        assistantId: binding.assistantId,
        action: textGuard.action,
        reason: textGuard.reason,
      });
    }
    askResult.answer = textGuard.text;

    const [firstChunk, ...remainingChunks] = splitDiscordMessage(
      askResult.answer,
    );

    await message.reply({
      content: firstChunk,
      allowedMentions: { repliedUser: false },
    });

    for (const chunk of remainingChunks) {
      await channel.send({
        content: chunk,
        allowedMentions: { repliedUser: false },
      });
    }

    if (askResult.files.length > 0) {
      const fetchRuntimeFile =
        deps.fetchRuntimeFile ??
        ((url: string, fileId: string) =>
          downloadRuntimeGeneratedFile(url, fileId, askInput));
      const { payloads, failed, blocked } = await buildRuntimeFilePayloads(
        binding.openclawUrl,
        askResult.files,
        fetchRuntimeFile,
      );

      if (payloads.length > 0) {
        await channel
          .send({
            content: "Here is the generated file.",
            allowedMentions: { repliedUser: false },
            files: payloads,
          })
          .catch(async () => {
            await channel.send?.({
              content: "I created the file, but couldn't upload it to Discord.",
              allowedMentions: { repliedUser: false },
            });
          });
      }

      if (blocked.length > 0) {
        await channel
          .send?.({
            content: SECRET_REFUSAL_MESSAGE,
            allowedMentions: { repliedUser: false },
          })
          .catch(() => undefined);
      }

      if (failed.length > 0 || (payloads.length === 0 && blocked.length === 0)) {
        await channel
          .send?.({
            content: "I created the file, but couldn't upload it to Discord.",
            allowedMentions: { repliedUser: false },
          })
          .catch(() => undefined);
      }

      deps.logger.info("Discord generated files delivered", {
        guildId,
        channelId,
        messageId: message.id,
        assistantId: binding.assistantId,
        fileCount: askResult.files.length,
        uploadedCount: payloads.length,
        failedCount: failed.length,
        contentTypes: askResult.files.map((file) => file.contentType),
        totalBytes: askResult.files.reduce((sum, file) => sum + file.size, 0),
      });
    }

    if (askResult.fileErrors.length > 0) {
      await channel
        .send?.({
          content: `Note: some generated files couldn't be prepared: ${askResult.fileErrors.join("; ")}`,
          allowedMentions: { repliedUser: false },
        })
        .catch(() => undefined);
    }

    await sendSkippedNote();
  } catch (error) {
    const referenceId = buildReferenceId(message.id);
    let runtimeHost: string | undefined;
    try {
      runtimeHost = new URL(binding.openclawUrl).hostname;
    } catch {
      runtimeHost = undefined;
    }

    deps.logger.error("Discord message handling failed", {
      guildId,
      channelId,
      messageId: message.id,
      assistantId: binding.assistantId,
      runtimeHost,
      referenceId,
      errorCategory: categorizeError(error),
      error: error instanceof Error ? error.message : String(error),
    });

    await message
      .reply({
        content: friendlyRuntimeErrorMessage(error, referenceId),
        allowedMentions: { repliedUser: false },
      })
      .catch((replyError) => {
        deps.logger.error("Failed to send Discord message error response", {
          guildId,
          channelId,
          messageId: message.id,
          error:
            replyError instanceof Error
              ? replyError.message
              : String(replyError),
        });
      });
  } finally {
    if (typingRefresh) {
      clearInterval(typingRefresh);
    }
  }
};

export const startDiscordMessageGateway = async () => {
  status.enabled = env.DISCORD_MESSAGE_GATEWAY_ENABLED === "true";

  if (!status.enabled) {
    return null;
  }

  if (startedClient) {
    return startedClient;
  }

  const client = new Client({
    intents: [
      GatewayIntentBits.Guilds,
      GatewayIntentBits.GuildMessages,
      GatewayIntentBits.MessageContent,
    ],
    partials: [Partials.Channel],
  });
  const processedMessages = createTtlMessageCache();
  const channelQueue = createPerChannelQueue();

  client.once(Events.ClientReady, () => {
    status.connected = true;
    logger.info("Discord message gateway connected");

    void resumeStaleAssistantJobs(client).catch((error) => {
      logger.error("Failed to resume assistant jobs after restart", {
        error: error instanceof Error ? error.message : String(error),
      });
    });
  });

  client.on(Events.ShardDisconnect, (event) => {
    status.connected = false;
    logger.warn("Discord message gateway disconnected", {
      code: event.code,
      reason: event.reason,
    });
  });

  client.on(Events.Error, (error) => {
    logger.error("Discord message gateway error", {
      error: error.message,
    });
  });

  client.on(Events.MessageCreate, (message) => {
    if (shouldIgnoreDiscordMessage(message, client.user?.id)) {
      return;
    }

    if (processedMessages.has(message.id)) {
      return;
    }

    processedMessages.add(message.id);

    const guildId = message.guildId;
    const channelId = message.channelId;

    if (!guildId || !channelId) {
      return;
    }

    void channelQueue.enqueue(`${guildId}:${channelId}`, () =>
      handleDiscordMessage(message, {
        logger,
        askAssistant: askOpenClawAssistant,
        runLongOperationJob: launchDiscordLongOperationJob,
        findBinding: ({ guildId: nextGuildId, channelId: nextChannelId }) =>
          DiscordAssistantBinding.findOne({
            discordGuildId: nextGuildId,
            discordChannelId: nextChannelId,
            enabled: true,
            responseMode: "all_messages",
          }),
      }),
    );
  });

  startedClient = client;

  try {
    await client.login(requireEnv("DISCORD_BOT_TOKEN"));
  } catch (error) {
    startedClient = null;
    status.connected = false;

    logger.error("Discord message gateway login failed", {
      error: error instanceof Error ? error.message : String(error),
    });

    throw error;
  }

  return client;
};

export const stopDiscordMessageGateway = async () => {
  if (!startedClient) {
    status.connected = false;
    return;
  }

  const client = startedClient;
  startedClient = null;
  status.connected = false;
  client.destroy();
  logger.info("Discord message gateway disconnected");
};
